---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 55b98bca584c2a5730fee0c8d5142f3c6fdb2539
    app.quarkus.io/vcs-uri: https://github.com/marek-mraz/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-22 - 08:34:06 +0000
  labels:
    app.kubernetes.io/name: history-query-manager
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: history-query-manager
