---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 910e1055dfdf61af26aff85bcd828d537c71631a
    app.quarkus.io/vcs-uri: https://github.com/marek-mraz/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-22 - 07:32:06 +0000
  labels:
    app.kubernetes.io/name: at-context-server
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: at-context-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: at-context-server
      app.kubernetes.io/version: 7.0.0
  endpoints:
    - scheme: http
      targetPort: 10097
      path: /q/metrics
      interval: 10s
      honorLabels: true
