---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 658bd9ad69858bd83cf16835165d6fca971d83b1
    app.quarkus.io/vcs-uri: https://github.com/marek-mraz/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-21 - 17:54:12 +0000
  labels:
    app.kubernetes.io/name: subscription-manager
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: subscription-manager
