---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: ee7f624dcc01faf64eb438cdebf88b6e15a9a43a
    app.quarkus.io/vcs-uri: https://github.com/marek-mraz/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-21 - 12:15:49 +0000
  labels:
    app.kubernetes.io/name: aio-runner
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: aio-runner
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aio-runner
      app.kubernetes.io/version: 7.0.0
  endpoints:
    - scheme: http
      targetPort: 9090
      path: /q/metrics
      interval: 10s
      honorLabels: true
