---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: ad732baf0fb16718b594ca0db65c1e85b5e7d972
    app.quarkus.io/vcs-uri: https://github.com/Mrazbb/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-21 - 12:08:19 +0000
  labels:
    app.kubernetes.io/name: aio-runner
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: aio-runner
