---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: f1c6d1311d29fd7aefdcb8a29e46f2bc6d028463
    app.quarkus.io/vcs-uri: https://github.com/marek-mraz/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-06-21 - 19:36:47 +0000
  labels:
    app.kubernetes.io/name: registry-subscription-manager
    app.kubernetes.io/version: 7.0.0
    app.kubernetes.io/managed-by: quarkus
  name: registry-subscription-manager
